/* Assistant Archer TEST - configurateur Pointe / Tube / Plume.
   Le spine reste calcule par app.js ; ce module compose ensuite les composants. */
(() => {
  'use strict';
  const state={part:'shaft',tubes:[],tube:null,point:null,vane:null,vanes:[],calculated:false};
  const norm=v=>String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
  const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
  const theme=()=>['cible','campagne','3d'].includes(document.getElementById('themeSelect')?.value)?document.getElementById('themeSelect').value:'cible';
  const bow=()=>document.getElementById('bowStyle')?.value==='barebow'?'barebow':'classique';
  const weight=()=>{const n=Number(document.getElementById('drawWeight')?.value);return Number.isFinite(n)?n:null;};
  function meta(name){try{return typeof normalizeModelKey==='function'&&typeof catalogState!=='undefined'?catalogState?.models?.[normalizeModelKey(name)]||null:null;}catch{return null;}}
  function brandName(value){try{if(value&&typeof brandLabel==='function')return brandLabel(value);}catch{}return({easton:'Easton',victory:'Victory',carbon:'Carbon Express',skylon:'Skylon',avalon:'Avalon'})[value]||value||'Marque non identifiee';}
  function inferBrand(name){try{if(typeof arrowCatalog==='undefined')return'';const wanted=norm(name).replace(/\s+\d{3,4}$/,'');for(const [brand,spines]of Object.entries(arrowCatalog||{}))for(const names of Object.values(spines||{}))if(Array.isArray(names)&&names.some(n=>norm(n).replace(/\s+\d{3,4}$/,'')===wanted))return brand;}catch{}return'';}
  function spine(text){return String(text||'').match(/spine\s+(?:conseill[eé]\s+)?(\d{3,4})/i)?.[1]||String(text||'').match(/(?:base|eq\.)\s+(\d{3,4})/i)?.[1]||'';}
  function material(m){const x=norm(m?.material);if(!x)return'Materiau non documente';if((x.includes('alu')||x.includes('aluminium'))&&x.includes('carbon'))return'Aluminium / carbone';if(x.includes('carbon')||x.includes('carbone'))return'Carbone';if(x.includes('alu')||x.includes('aluminium'))return'Aluminium';return String(m.material);}
  function diameter(m){const raw=Array.isArray(m?.diameters)?m.diameters[0]:m?.diameter;if(!raw)return'diametre non documente';return({thin:'tube fin',standard:'diametre standard',large:'gros diametre'})[norm(raw)]||String(raw);}
  function collectTubes(){const result=document.getElementById('result');if(!result)return[];const pref=document.getElementById('preferredBrand')?.value||'';const out=[];result.querySelectorAll('ul').forEach(list=>{if(list.closest('.merchant-panel,.merchant-block'))return;const marker=`${list.previousElementSibling?.textContent||''} ${list.parentElement?.querySelector(':scope > .mini-card-subtitle')?.textContent||''}`;if(!/mod[eè]les\s+(conseill|coh[eé]rent)/i.test(marker))return;const card=list.closest('[data-aa-brand]');list.querySelectorAll(':scope > li').forEach(li=>{const strong=li.querySelector('strong');if(!strong)return;const model=strong.textContent.trim();if(!model)return;const brand=card?.dataset?.aaBrand||(pref!=='all'?pref:inferBrand(model));const s=spine(li.textContent);out.push({id:`${brand||'unknown'}|${norm(model)}|${s||'na'}`,brand,model,spine:s,meta:meta(model)});});});const seen=new Set();return out.filter(x=>{const k=x.id;if(seen.has(k))return false;seen.add(k);return true;});}
  function pointChoices(tube){const direct=Array.isArray(tube?.meta?.pointChoices)?tube.meta.pointChoices.map(Number).filter(Number.isFinite):[];return[...new Set(direct)].sort((a,b)=>a-b);}
  function pointRange(tube){const range=Array.isArray(tube?.meta?.pointRange)?tube.meta.pointRange.map(Number):[];return range.length>=2&&range.every(Number.isFinite)?[Math.min(...range),Math.max(...range)]:null;}
  function vaneScore(v){let score=0,reasons=[];const d=Array.isArray(state.tube?.meta?.diameters)?norm(state.tube.meta.diameters[0]):'';if(v.disciplines?.includes(theme())){score+=4;reasons.push('discipline coherente');}if(v.bowStyles?.includes(bow())){score+=2;reasons.push('type d arc coherent');}if(!d||v.diameters?.includes(d)){score+=2;if(d)reasons.push('diametre coherent');}const w=weight();if(!v.drawWeight||!Number.isFinite(w)||(w>=v.drawWeight[0]&&w<=v.drawWeight[1]))score++;else score-=2;return{score,reasons};}
  function ensure(){let el=document.getElementById('arrowBuilder');if(el)return el;const result=document.getElementById('result');if(!result)return null;el=document.createElement('section');el.id='arrowBuilder';el.className='card arrow-builder';el.innerHTML=`<div class="arrow-builder-head"><div><p class="arrow-builder-kicker">Choisir ou changer mes fleches</p><h2>Construire ma fleche</h2></div><p class="arrow-builder-state" id="arrowBuilderState"></p></div><p class="arrow-builder-intro">Touchez une partie de la fleche. Le tube reste determine par le moteur technique actuel ; pointe et plume viennent ensuite.</p><div class="arrow-assembly" role="tablist" aria-label="Composants de la fleche"><button type="button" class="arrow-part arrow-part-point" data-arrow-part="point"><span class="arrow-part-art"></span><span>Pointe</span></button><button type="button" class="arrow-part arrow-part-shaft" data-arrow-part="shaft"><span class="arrow-part-art"></span><span>Tube</span></button><button type="button" class="arrow-part arrow-part-vane" data-arrow-part="vane"><span class="arrow-part-art">🪶</span><span>Plume</span></button></div><div class="arrow-builder-summary" id="arrowBuilderSummary"></div><div class="arrow-builder-panel" id="arrowBuilderPanel"></div>`;result.insertAdjacentElement('afterend',el);el.querySelectorAll('[data-arrow-part]').forEach(b=>b.addEventListener('click',()=>{state.part=b.dataset.arrowPart;render();}));return el;}
  function summary(){const el=document.getElementById('arrowBuilderSummary');if(!el)return;el.innerHTML=`<div><span>Tube</span><strong>${state.tube?`${esc(state.tube.model)}${state.tube.spine?` · ${esc(state.tube.spine)}`:''}`:'A choisir'}</strong></div><div><span>Pointe</span><strong>${state.point?`${state.point} gr`:'A choisir'}</strong></div><div><span>Plume</span><strong>${state.vane?esc(state.vane.model):'A choisir'}</strong></div>`;}
  function tubePanel(el){if(!state.calculated){el.innerHTML='<h3>Tube</h3><p>Lancez le calcul au-dessus. Les tubes affiches ici seront ceux de la recommandation technique.</p>';return;}el.innerHTML=`<div class="arrow-builder-panel-head"><div><h3>Tube</h3><p>Choisissez parmi les modeles techniquement proposes.</p></div><span class="arrow-builder-count">${state.tubes.length} modele${state.tubes.length>1?'s':''}</span></div><div class="arrow-component-list">${state.tubes.map((t,i)=>{const choices=pointChoices(t),range=pointRange(t);const pointInfo=choices.length?`<p>Poids de pointe explicitement documentes : <strong>${choices.map(x=>`${x} gr`).join(' · ')}</strong></p>`:range?`<p>Plage technique de pointe : <strong>${range[0]}–${range[1]} gr</strong> · references et poids exacts encore a documenter.</p>`:'<p class="muted">Pointe exacte encore a documenter pour ce modele.</p>';return`<article class="arrow-component-card${state.tube?.id===t.id?' is-selected':''}"><div class="arrow-component-card-head"><div><span class="arrow-component-brand">${esc(brandName(t.brand))}</span><h4>${esc(t.model)}</h4></div>${i===0?'<span class="arrow-builder-badge">Suggestion</span>':''}</div><p class="arrow-component-specs">${t.spine?`Spine ${esc(t.spine)} · `:''}${esc(material(t.meta))} · ${esc(diameter(t.meta))}</p>${pointInfo}<button type="button" class="secondary arrow-select-component" data-tube="${esc(t.id)}">${state.tube?.id===t.id?'✓ Tube selectionne':'Utiliser ce tube'}</button></article>`;}).join('')}</div>`;el.querySelectorAll('[data-tube]').forEach(b=>b.addEventListener('click',()=>{state.tube=state.tubes.find(x=>x.id===b.dataset.tube)||null;state.point=null;state.vane=null;render();}));}
  function pointPanel(el){if(!state.tube){el.innerHTML='<h3>Pointe</h3><p>Selectionnez d abord un tube : les pointes seront filtrees a partir de ce tube, jamais l inverse.</p>';return;}const choices=pointChoices(state.tube),range=pointRange(state.tube);let body='';if(choices.length){body=`<div class="arrow-point-choices">${choices.map(w=>`<button type="button" class="arrow-point-choice${state.point===w?' is-selected':''}" data-point="${w}"><strong>${w} gr</strong><span>poids documente</span></button>`).join('')}</div><p class="arrow-builder-callout">Une pointe plus lourde tend a assouplir dynamiquement la fleche ; une plus legere tend a la raidir. Validation finale au tir.</p>`;}else if(range){body=`<div class="arrow-builder-empty"><strong>Plage technique connue : ${range[0]}–${range[1]} gr.</strong><p>Les poids commerciaux et references compatibles ne sont pas encore relies a une source fabricant precise. Ils ne sont donc pas selectionnables pour l instant.</p></div>`;}else{body='<div class="arrow-builder-empty"><strong>Reference exacte pas encore documentee.</strong><p>On n invente pas de pointe compatible : la liaison aux references fabricant sera le prochain enrichissement.</p></div>';}el.innerHTML=`<h3>Pointe pour ${esc(state.tube.model)}</h3><p>On utilise uniquement les donnees deja associees a ce tube.</p>${body}<p class="muted">Le nom commercial de la pointe n apparaitra que lorsqu il sera relie a une source fabricant precise.</p>`;el.querySelectorAll('[data-point]').forEach(b=>b.addEventListener('click',()=>{state.point=Number(b.dataset.point);render();}));}
  function vanePanel(el){if(!state.vanes.length){el.innerHTML='<h3>Plumes</h3><p>Chargement du catalogue de plumes sourcees…</p>';return;}const list=state.vanes.map(v=>({v,m:vaneScore(v)})).sort((a,b)=>b.m.score-a.m.score||a.v.manufacturer.localeCompare(b.v.manufacturer));el.innerHTML=`<div class="arrow-builder-panel-head"><div><h3>Plumes</h3><p>Classement selon discipline, type d arc et diametre quand il est documente.</p></div><span class="arrow-builder-count">${list.length} references sourcees</span></div><div class="arrow-component-list">${list.map(({v,m},i)=>`<article class="arrow-component-card${state.vane?.id===v.id?' is-selected':''}"><div class="arrow-component-card-head"><div><span class="arrow-component-brand">${esc(v.manufacturer)} · ${esc(v.family)}</span><h4>${esc(v.model)}</h4></div><span class="arrow-builder-badge${i>2?' is-secondary':''}">${m.score>=7?'Tres coherente':m.score>=5?'A envisager':'Usage specifique'}</span></div><p class="arrow-component-specs">Longueur ${esc(v.length)}${v.weight?` · ${esc(v.weight)}`:''} · ${esc(v.stiffness)}</p><p>${esc(v.use)}</p>${m.reasons.length?`<p class="muted">Pourquoi ici : ${esc(m.reasons.join(' · '))}.</p>`:''}<p class="arrow-source"><a href="${esc(v.sourceUrl)}" target="_blank" rel="noopener noreferrer">Source fabricant : ${esc(v.sourceLabel)}</a></p><button type="button" class="secondary arrow-select-component" data-vane="${esc(v.id)}">${state.vane?.id===v.id?'✓ Plume selectionnee':'Choisir cette plume'}</button></article>`).join('')}</div>`;el.querySelectorAll('[data-vane]').forEach(b=>b.addEventListener('click',()=>{state.vane=state.vanes.find(v=>v.id===b.dataset.vane)||null;render();}));}
  function render(){const root=ensure();if(!root)return;root.querySelectorAll('[data-arrow-part]').forEach(b=>{const a=b.dataset.arrowPart===state.part;b.classList.toggle('is-active',a);b.setAttribute('aria-selected',a?'true':'false');});const s=document.getElementById('arrowBuilderState');if(s)s.textContent=state.calculated?(state.tube?`Tube selectionne : ${state.tube.model}${state.tube.spine?` · ${state.tube.spine}`:''}`:'Choisissez un tube propose.'):'Lancez d abord le calcul du tube.';summary();const p=document.getElementById('arrowBuilderPanel');if(!p)return;state.part==='point'?pointPanel(p):state.part==='vane'?vanePanel(p):tubePanel(p);}
  function refresh(){state.tubes=collectTubes();state.calculated=state.tubes.length>0;if(state.tube)state.tube=state.tubes.find(x=>x.id===state.tube.id)||null;if(!state.tube&&state.tubes.length)state.tube=state.tubes[0];if(!state.tube){state.point=null;state.vane=null;}render();}
  async function loadVanes(){try{const r=await fetch('./arrow-components.json',{cache:'no-store'});if(!r.ok)throw new Error(String(r.status));const data=await r.json();state.vanes=Array.isArray(data.vanes)?data.vanes:[];}catch(e){console.warn('[Assistant Archer] catalogue composants indisponible',e);state.vanes=[];}render();}
  function install(){if(!ensure())return;const result=document.getElementById('result');if(result&&!result.dataset.arrowBuilderObserved){result.dataset.arrowBuilderObserved='1';new MutationObserver(()=>{clearTimeout(install.timer);install.timer=setTimeout(refresh,50);}).observe(result,{childList:true,subtree:true});}document.getElementById('spine-form')?.addEventListener('submit',()=>setTimeout(refresh,150));document.getElementById('themeSelect')?.addEventListener('change',render);document.getElementById('bowStyle')?.addEventListener('change',render);loadVanes();refresh();}
  window.AssistantArcherArrowBuilder=Object.freeze({refresh,version:'v50'});
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',install,{once:true}):install();
})();
