/* Correctifs issus de l'audit du 10/08/2026. Point d'entree unique des modules additionnels TEST. */
(() => {
  const originalNormalizeInput = window.normalizeInput;
  const originalScoreModel = window.scoreModel;
  const originalEastonCarbonRecommendation = window.eastonCarbonRecommendation;
  const originalEastonAluRecommendation = window.eastonAluRecommendation;
  const originalVictoryRecurveRecommendation = window.victoryRecurveRecommendation;
  const originalVictoryVxtRecommendation = window.victoryVxtRecommendation;
  const originalCarbonExpressRecommendation = window.carbonExpressRecommendation;
  const originalComputeArcSetup = window.computeArcSetup;
  const originalRenderArcSetup = window.renderArcSetup;
  const originalRenderBarebowArcSetup = window.renderBarebowArcSetup;
  function roundedLengthInRange(input,min,max,label){const roundedLength=Math.round(input.arrowLength);if(roundedLength<min||roundedLength>max)return{ok:false,message:`Longueur hors tableau ${label} (${min} a ${max} pouces).`};return null}
  window.normalizeInput=function(input){if(input.shaftMaterial!=="all")return originalNormalizeInput(input);return{...input,shootingProfile:"recurve_all",shootingEnvironment:"mixed",discipline:"target"}};
  window.scoreModel=function(modelName,input,profile){if(input.shaftMaterial!=="all")return originalScoreModel(modelName,input,profile);const outdoor=originalScoreModel(modelName,{...input,shootingProfile:"recurve_outdoor",shootingEnvironment:"outdoor"},profile),indoor=originalScoreModel(modelName,{...input,shootingProfile:"recurve_indoor",shootingEnvironment:"indoor"},profile);return outdoor.score>=indoor.score?outdoor:indoor};
  window.eastonCarbonRecommendation=(input)=>roundedLengthInRange(input,21,34,"Easton carbone")||originalEastonCarbonRecommendation(input);window.eastonAluRecommendation=(input)=>roundedLengthInRange(input,21,32,"Easton alu")||originalEastonAluRecommendation(input);window.victoryRecurveRecommendation=(input)=>roundedLengthInRange(input,23,31,"Victory recurve")||originalVictoryRecurveRecommendation(input);window.victoryVxtRecommendation=function(input){if(roundedLengthInRange(input,23,31,"Victory VXT"))return null;return originalVictoryVxtRecommendation(input)};window.carbonExpressRecommendation=function(input){const light=input.drawWeight<=34&&input.arrowLength<=27;return(light?roundedLengthInRange(input,21,27,"Carbon Express light recurve"):roundedLengthInRange(input,23,32,"Carbon Express recurve series"))||originalCarbonExpressRecommendation(input)};
  window.computeArcSetup=function(input){const setup=originalComputeArcSetup(input),min=2,max=6,a=setup.actualTiller,target=a<min?min:a>max?max:a,expected=Math.round((input.upperTiller-target)*10)/10;setup.tillerRange=[min,max];setup.lowerTiller=expected;setup.lowerGap=Math.round((input.lowerTillerMeasured-expected)*10)/10;setup.tillerTarget=target;setup.tillerAction=a>=min&&a<=max?`Tiller dans la plage de depart conseillee (+${min} a +${max} mm). Conserver puis affiner au tir si necessaire.`:`Tiller hors plage de depart conseillee (+${min} a +${max} mm). Corriger progressivement vers la limite la plus proche.`;setup.adjustment=a>=min&&a<=max?{status:"OK - dans la plage conseillee",advice:`Le tiller mesure (+${a.toFixed(1)} mm) est compris entre +${min} et +${max} mm. Ne modifiez pas les vis uniquement pour viser +6 mm.`}:window.buildTillerAdjustment(a,target);if(Array.isArray(setup.checks))setup.checks=setup.checks.map(line=>line.startsWith("Tiller :")?`Tiller : plage de depart conseillee entre +${min} et +${max} mm, a affiner selon le comportement de l'arc.`:line);return setup};
  window.renderArcSetup=function(input){const result=originalRenderArcSetup(input),output=document.getElementById("arcSetupResult");if(output)output.innerHTML=output.innerHTML.replace(/<strong>Tiller positif vise<\/strong> : \+[^<]+ mm/,'<strong>Plage de tiller conseillee</strong> : +2 a +6 mm').replace(/<strong>Tiller<\/strong> : base visee \+[^|]+\|/,'<strong>Tiller</strong> : plage conseillee +2 a +6 mm |');return result};
  window.renderBarebowArcSetup=function(input){
    if(typeof els!=="undefined"&&els.arcBbBandMeasured){els.arcBbBandMeasured.value=Number.isFinite(input.braceMeasured)?String(input.braceMeasured):"";}
    const classical=window.computeArcSetup;window.computeArcSetup=function(i){const s=originalComputeArcSetup(i),min=-2,max=2,a=s.actualTiller,target=Math.max(min,Math.min(max,a)),expected=Math.round((i.upperTiller-target)*10)/10;s.tillerRange=[min,max];s.lowerTiller=expected;s.lowerGap=Math.round((i.lowerTillerMeasured-expected)*10)/10;s.tillerTarget=target;s.tillerAction=a>=min&&a<=max?`Tiller faible/proche de zero (${a.toFixed(1)} mm) : conserver comme base si l'arc est stable, puis valider au tir sur plusieurs crawls.`:`Tiller ${a.toFixed(1)} mm : verifier d'abord la recommandation fabricant puis revenir progressivement vers un tiller faible si necessaire.`;s.adjustment=a>=min&&a<=max?{status:"Base barebow coherente",advice:"Ne cherchez pas a atteindre exactement 0 mm. Validez le comportement de l'arc sur plusieurs crawls."}:window.buildTillerAdjustment(a,target);return s};try{return originalRenderBarebowArcSetup(input)}finally{window.computeArcSetup=classical}};
  document.querySelectorAll(".arc-classic-only p").forEach(p=>{if(p.textContent.includes("Repere de base"))p.innerHTML='Le <strong>band</strong> depend surtout de la taille d\'arc. Le <strong>tiller positif</strong> se calcule ainsi : <strong>tiller haut - tiller bas</strong>. Repere de depart : entre <strong>+2 et +6 mm</strong>.'});
  const upperTillerInput=document.getElementById("upperTiller"),lowerTillerInput=document.getElementById("lowerTillerMeasured");if(upperTillerInput){upperTillerInput.value="";upperTillerInput.placeholder="Ex : 222"}if(lowerTillerInput){lowerTillerInput.value="";lowerTillerInput.placeholder="Ex : 218"}
  localStorage.setItem("sw-cleanup-v1","done");if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));
  let deferredInstallPrompt=null;const isStandalone=()=>window.matchMedia("(display-mode: standalone)").matches||window.navigator.standalone===true;const isIOS=()=>/iphone|ipad|ipod/i.test(navigator.userAgent);
  function installAppSettingsControl(){const body=document.querySelector(".app-settings-body");if(!body||document.getElementById("installAppBtn")||isStandalone())return;const block=document.createElement("div");block.className="app-install-setting";block.style.cssText="margin-top:.9rem;padding-top:.9rem;border-top:1px solid rgba(0,0,0,.12)";const button=document.createElement("button");button.type="button";button.id="installAppBtn";button.textContent="Installer l'application";const status=document.createElement("p");status.id="installAppStatus";status.style.cssText="margin:.5rem 0 0;font-size:.9em";status.textContent="Ajoute Assistant Archer comme une application sur le telephone.";button.onclick=async()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();const choice=await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;status.textContent=choice.outcome==="accepted"?"Installation lancee.":"Installation annulee."}else if(isIOS())status.textContent="Sur iPhone/iPad : Safari > Partager > Ajouter a l'ecran d'accueil.";else status.textContent="Ouvrez le menu du navigateur puis choisissez Installer l'application ou Ajouter a l'ecran d'accueil."};block.append(button,status);body.appendChild(block)}
  window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstallPrompt=e;const s=document.getElementById("installAppStatus");if(s)s.textContent="Pret a installer : touchez Installer l'application."});window.addEventListener("appinstalled",()=>{deferredInstallPrompt=null;document.querySelector('.app-install-setting')?.remove();});installAppSettingsControl();
  function applyBrandIdentity(){document.title="Assistant Archer";let icon=document.querySelector('link[rel="icon"]');if(icon){icon.href="icon-assistant-archer-v11.svg";icon.type="image/svg+xml"}const h=document.querySelector('.hero h1');if(h)h.textContent="Assistant Archer";const p=document.querySelector('.hero > p');if(p)p.textContent="Choisir ses fleches, regler son arc et garder ses reperes.";if(!document.getElementById('aaBrandStyle')){const s=document.createElement('style');s.id='aaBrandStyle';s.textContent=`.app-settings{border-color:var(--line)}.app-settings[open]{box-shadow:0 14px 30px rgba(9,31,55,.18)}.tab-nav{display:none!important}`;document.head.appendChild(s)}}
  applyBrandIdentity();
  function enhancePointAdvice(){const result=document.getElementById('result');if(!result)return;const paragraphs=[...result.querySelectorAll('p')];const point=paragraphs.find(p=>p.textContent.trim().startsWith('Pointe conseillee'));if(!point||point.dataset.pointGuidance==='1')return;const match=point.textContent.match(/Pointe conseillee\s*:\s*(\d+)\s*gr.*?(\d+)\s*-\s*(\d+)\s*gr/i);if(!match)return;const recommended=Number(match[1]),min=Number(match[2]),max=Number(match[3]);point.dataset.pointGuidance='1';point.innerHTML=`<strong>Pointe conseillee</strong> : ${recommended} gr <span class="result-subvalue">(plage fabricant ${min}-${max} gr)</span>`;const quick=paragraphs.find(p=>p.textContent.trim().startsWith('Ajustement rapide'));if(quick)quick.innerHTML='<strong>Affinage au tir</strong> : une pointe plus lourde assouplit dynamiquement la fleche ; une pointe plus legere la raidit. Restez dans la plage compatible du tube.';}
  const resultPanel=document.getElementById('result');if(resultPanel)new MutationObserver(enhancePointAdvice).observe(resultPanel,{childList:true,subtree:true});enhancePointAdvice();
  const originalRenderDeals=window.renderDeals;
  function escapeMerchantText(value){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[ch]));}
  function merchantPriceValue(price){const match=String(price||'').replace(/\s/g,'').replace(',','.').match(/(\d+(?:\.\d+)?)/);return match?Number(match[1]):Number.POSITIVE_INFINITY;}
  function compatibleMerchantDeals(preferredBrand,shaftMaterial,bowType,shootingProfile,allowedBrands){const list=(typeof dealsState!=='undefined'&&Array.isArray(dealsState?.deals))?dealsState.deals:[];return list.filter(deal=>{const brandOk=preferredBrand==='all'||deal.brand===preferredBrand;const visibleBrandOk=!allowedBrands||allowedBrands.includes(deal.brand);const materialOk=shaftMaterial==='all'||deal.material===shaftMaterial;const bowOk=!deal.bowTypes||deal.bowTypes.includes(bowType);const outdoorOk=shootingProfile!=='recurve_outdoor'||deal.material==='carbon';return brandOk&&visibleBrandOk&&materialOk&&bowOk&&outdoorOk;}).sort((a,b)=>merchantPriceValue(a.price)-merchantPriceValue(b.price));}
  if(typeof originalRenderDeals==='function')window.renderDeals=function(preferredBrand,shaftMaterial,bowType,shootingProfile,allowedBrands=null,recommendedModels=[]){const exact=originalRenderDeals(preferredBrand,shaftMaterial,bowType,shootingProfile,allowedBrands,recommendedModels);if(exact&&!exact.includes('Aucune offre marchande')&&!exact.includes('Aucune offre correspondant'))return exact;const fallback=compatibleMerchantDeals(preferredBrand,shaftMaterial,bowType,shootingProfile,allowedBrands).slice(0,8);if(!fallback.length)return exact;const groups=fallback.reduce((acc,deal)=>{(acc[deal.shop]??=[]).push(deal);return acc;},{});const content=Object.entries(groups).map(([shop,deals])=>`<li class="merchant-shop"><p class="merchant-shop-name">${escapeMerchantText(shop)}</p><ul class="merchant-deals">${deals.map(deal=>`<li><a href="${escapeMerchantText(deal.url)}" target="_blank" rel="noopener noreferrer">${escapeMerchantText(deal.title)}</a> - ${escapeMerchantText(deal.price)}</li>`).join('')}</ul></li>`).join('');return `<section class="merchant-block"><p class="merchant-intro">Aucune offre exacte pour le modele conseille. Voici des offres compatibles avec la marque, la matiere et le type d arc :</p><ul class="merchant-shops">${content}</ul></section>`;};
  function loadModule(src,key){if(document.querySelector(`script[data-${key}]`))return;const s=document.createElement("script");s.src=src;s.async=false;s.setAttribute(`data-${key}`,"true");document.head.appendChild(s);}
  loadModule("barebow-guidance.js?v=20260815a","barebow-guidance");
  loadModule("ui-refactor.js?v=20260815a","ui-refactor");
  loadModule("expert-audit.js?v=20260814b","expert-audit");
  loadModule("onboarding.js?v=20260810d","onboarding");
  queueMicrotask(()=>{try{window.applyBowStyle(window.currentBowStyle())}catch{}});
})();