/* TEST v31 : aligne les offres marchands sur toutes les marques/modeles proposes. */
(() => {
 const VERSION='2026.08.18-test.31';
 function norm(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim()}
 function settings(){const s=document.querySelector('.app-settings-toggle');if(s)s.innerHTML='<span class="gear-icon" aria-hidden="true">⚙</span><span class="settings-label">Réglages Paramètres</span>';const b=document.querySelector('.app-settings-body');if(!b)return;const sv=document.getElementById('appVersionStatic');if(sv)sv.textContent='Version : '+VERSION;document.getElementById('appVersionInfo')?.remove()}
 function labels(){const g=document.getElementById('aaNeedsGuide');if(!g)return;const n=g.querySelector('[data-go="notebook"]'),s=g.querySelector('[data-go="sight"]');if(n)n.textContent='Enregistrer / retrouver mes reglages';if(s)s.textContent='Enregistrer / consulter mes reperes'}
 function packageLabel(title){const t=norm(title);if(/\b(douzaine|lot de 12|12 tubes|12 futs|12 fleches)\b/.test(t))return'lot de 12';if(/\b(unite|a l unite)\b/.test(t)||(/\btube\b/.test(t)&&!/\btubes\b/.test(t)))return'prix a l unite';return'conditionnement a verifier'}
 function canonicalModel(v){let s=norm(v).replace(/\b(spine|r)\s*\d{3,4}(?:\s*[-–]\s*\d{3,4})?\b/g,'').replace(/\b\d{3,4}\b/g,'').trim();const aliases=[['preminens','premiens'],['vap target v1','vap target'],['vap target elite','vap target'],['vap target sport','vap target'],['vap v3','vap'],['vap sport','vap'],['vxt elite v1','vxt elite'],['predator ii','predator ii'],['maxima red','maxima red'],['nano pro rz','nano-pro rz'],['nano pro xtreme','nano-pro xtreme'],['medallion xr','medallion xr'],['superdrive micro','superdrive micro'],['xx75 platinum plus','xx75 platinum plus']];for(const[a,b]of aliases)if(s.includes(a))return b;return s}
 function proposedModels(result){const set=new Set();const textNodes=[...result.querySelectorAll('li,p')];for(const el of textNodes){if(el.closest('.merchant-block'))continue;const text=(el.textContent||'').trim();let m=text.match(/^(?:•\s*)?([^—:\n]+?)(?:\s+R?\d{3,4}(?:[-–]\d{3,4})?)?\s*(?:—|:)/);if(m){const c=canonicalModel(m[1]);if(c&&c.length>2&&!/^(pourquoi|important|plage fabricant|sources|confiance|note)$/i.test(c))set.add(c)}}return set}
 function matches(title,key){const t=canonicalModel(title),k=canonicalModel(key);if(!k)return false;if(k==='vap')return /\bvap\b/.test(t)&&!t.includes('vap target');return t.includes(k)||k.includes(t)}
 function alignMerchants(){const r=document.getElementById('result');if(!r)return;const blocks=[...r.querySelectorAll('.merchant-block')];if(!blocks.length)return;const models=proposedModels(r);if(!models.size)return;blocks.forEach(block=>{const sig=[...models].sort().join('|');if(block.dataset.allBrandsFilter===sig)return;block.dataset.allBrandsFilter=sig;let kept=0;block.querySelectorAll('.merchant-deals li').forEach(li=>{const title=li.querySelector('a')?.textContent||li.textContent||'';const found=[...models].find(k=>matches(title,k));if(!found){li.remove();return}kept++;li.querySelector('.aa-offer-meta')?.remove();const meta=document.createElement('div');meta.className='aa-offer-meta';meta.style.cssText='font-size:.88em;margin-top:.2rem;opacity:.82';meta.textContent=`Correspond au modele propose : ${found} · ${packageLabel(title)}`;li.appendChild(meta)});block.querySelectorAll('.merchant-shop').forEach(shop=>{if(!shop.querySelector('.merchant-deals li'))shop.remove()});let intro=block.querySelector('.merchant-intro');if(!intro){intro=document.createElement('p');intro.className='merchant-intro';block.prepend(intro)}intro.innerHTML=kept?'<strong>Offres marchands cohérentes :</strong> uniquement les marques et modèles réellement proposés dans le résultat ci-dessus. Les prix proviennent de la base marchands mise à jour quotidiennement.':'<strong>Aucune offre correspondante actuellement :</strong> la base quotidienne ne contient pas encore de prix pour les modèles proposés. Aucune offre hors recommandation n’est affichée.'})}
 function run(){settings();labels();alignMerchants();document.documentElement.dataset.testFixVersion=VERSION}
 let q=false;function schedule(){if(q)return;q=true;requestAnimationFrame(()=>{q=false;run()})}
 function init(){schedule();new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true,characterData:true});document.addEventListener('submit',()=>{setTimeout(schedule,0);setTimeout(schedule,120);setTimeout(schedule,450)},true);document.addEventListener('change',()=>setTimeout(schedule,80),true)}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
