/* TEST v34 : ajoute les grandes references Easton compatibles + explications + marchands alignes. */
(() => {
 const VERSION='2026.08.18-test.34';
 function norm(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim()}
 function settings(){const s=document.querySelector('.app-settings-toggle');if(s)s.innerHTML='<span class="gear-icon" aria-hidden="true">⚙</span><span class="settings-label">Réglages Paramètres</span>';const b=document.querySelector('.app-settings-body');if(!b)return;const sv=document.getElementById('appVersionStatic');if(sv)sv.textContent='Version : '+VERSION;document.getElementById('appVersionInfo')?.remove()}
 function labels(){const g=document.getElementById('aaNeedsGuide');if(!g)return;const n=g.querySelector('[data-go="notebook"]'),s=g.querySelector('[data-go="sight"]');if(n)n.textContent='Enregistrer / retrouver mes reglages';if(s)s.textContent='Enregistrer / consulter mes reperes'}
 function packageLabel(title){const t=norm(title);if(/\b(douzaine|lot de 12|12 tubes|12 futs|12 fleches)\b/.test(t))return'lot de 12';if(/\b(unite|a l unite)\b/.test(t)||(/\btube\b/.test(t)&&!/\btubes\b/.test(t)))return'prix a l unite';return'conditionnement a verifier'}
 const ALIASES={'avance':['avance','avance sport'],'superdrive micro':['superdrive micro'],'vector':['vector'],'vector ready to shoot':['vector ready to shoot','vector rts'],'x10':['x10'],'a/c/e':['a/c/e','ace'],'x10 parallel pro 4 mm':['x10 parallel pro 4 mm','4mm x10 parallel pro','x10 parallel pro'],'x10 parallel pro 3.2 mm':['3.2mm x10 parallel pro','3 2mm x10 parallel pro'],'x7':['x7'],'x23':['x23'],'rx7':['rx7'],'xx75 platinum plus':['xx75 platinum plus'],'vap v3':['vap v3'],'vap sport':['vap sport'],'vap target':['vap target','vap target v1','vap target elite','vap target sport'],'vxt elite v1':['vxt elite v1','vxt elite'],'vap gamer v3':['vap gamer v3'],'vft gamer v3':['vft gamer v3'],'v-tac 23 elite':['v-tac 23 elite','v tac 23 elite'],'vforce':['vforce'],'predator ii':['predator ii'],'maxima red':['maxima red'],'hunter xt':['hunter xt'],'trojan':['trojan'],'nano-pro rz':['nano pro rz','nano-pro rz'],'nano-pro xtreme':['nano pro xtreme','nano-pro xtreme'],'medallion xr':['medallion xr'],'nano sst':['nano sst'],'brixxon':['brixxon'],'radius':['radius'],'premiens':['premiens','preminens'],'performa':['performa'],'precium':['precium'],'paragon':['paragon'],'edge':['edge']};
 const WHY={'avance':'Retenue pour son tube carbone fin orienté cible : un choix cohérent pour le classique et la progression vers la compétition.','superdrive micro':'Retenue pour son petit diamètre et son orientation performance extérieure ; intéressante lorsque la discipline privilégie la tenue au vent, le campagne ou le 3D.','vector':'Retenue comme solution carbone polyvalente et accessible, adaptée au club, à la progression et au loisir cible.','vector ready to shoot':'Retenue comme version prête à tirer du Vector, pratique pour une configuration simple et immédiatement exploitable.','x10':'Référence historique du tir olympique en arc classique : tube aluminium/carbone très fin, conçu pour la précision à longue distance et la réduction de la dérive au vent.','a/c/e':'Référence aluminium/carbone légère et éprouvée, particulièrement pertinente pour la cible et les longues distances lorsque sa taille correspond.','x10 parallel pro 4 mm':'Tube aluminium/carbone de compétition à profil parallèle 4 mm, pertinent en cible, campagne et arc nu lorsque la taille disponible correspond.','x10 parallel pro 3.2 mm':'Nouvelle référence très petit diamètre de la famille X10, pensée pour la compétition extérieure et utilisable en classique lorsque la taille disponible correspond.','vap v3':'Retenue pour son petit diamètre carbone et son orientation cible/performance.','vap sport':'Retenue comme option carbone plus accessible de la famille VAP, adaptée à la progression en cible.','vap target':'Retenue pour sa conception dédiée à la cible et à la précision.','vxt elite v1':'Retenue comme tube cible haut de gamme lorsque son spine disponible correspond à la configuration.','vap gamer v3':'Retenue comme tube carbone polyvalent lorsque la pratique et le niveau recherchés correspondent à sa gamme.','predator ii':'Retenue comme tube carbone robuste et polyvalent, adapté à une pratique loisir ou parcours selon la configuration.','maxima red':'Retenue pour sa conception carbone orientée performance lorsque la discipline et le spine la rendent pertinente.','brixxon':'Retenue comme tube polyvalent pour la cible, l’initiation ou l’entraînement selon la configuration.','radius':'Retenue comme tube carbone accessible et polyvalent pour la progression.','premiens':'Retenue comme tube cible orienté précision lorsque sa plage de spine convient.','performa':'Retenue pour son orientation cible et performance lorsque la configuration correspond.','precium':'Retenue pour son orientation précision/cible lorsque la configuration correspond.','paragon':'Retenue comme tube carbone de cible orienté performance lorsque son spine convient.','edge':'Retenue comme option carbone polyvalente lorsque la configuration et la discipline correspondent.'};
 const EASTON_REFERENCES=[
  {key:'x10',name:'X10',material:'Aluminium/Carbone — hybride',spines:[325,350,380,410,450,500,550,600,650,700,750,830,900,1000],bows:['recurve']},
  {key:'a/c/e',name:'A/C/E',material:'Aluminium/Carbone — hybride',spines:[370,400,430,470,520,570,620,670,720,780,850,920,1000,1100,1250],bows:['recurve','compound']},
  {key:'x10 parallel pro 4 mm',name:'X10 Parallel Pro 4 mm',material:'Aluminium/Carbone — hybride',spines:[250,300,340,380,420,470,520,570,610,660,710,810,880,1000,1150],bows:['recurve','barebow','compound']},
  {key:'x10 parallel pro 3.2 mm',name:'X10 Parallel Pro 3,2 mm',material:'Aluminium/Carbone — hybride',spines:[340,380,420,460,500,550,600,650,700,750,800,900,1000],bows:['recurve','barebow','compound']}
 ];
 function canonical(v){const t=' '+norm(v)+' ';for(const [key,arr] of Object.entries(ALIASES)){for(const a of arr){const n=norm(a);if(t.includes(' '+n+' ')||t.includes(n))return key}}return''}
 function currentBow(){const raw=norm(document.getElementById('bowStyle')?.value||document.getElementById('bowType')?.value||document.documentElement.dataset.bowType||'recurve');return raw.includes('bare')||raw.includes('nu')?'barebow':raw.includes('compound')||raw.includes('poul')?'compound':'recurve'}
 function eastonRange(r){const t=r.textContent||'';const m=t.match(/(?:base\s+)?(\d{3,4})\s*[-–]\s*(\d{3,4})\s*\/\s*eq\.?\s*(\d{3,4})/i)||t.match(/plage fabricant\s*:\s*(\d{3,4})\s*[-–]\s*(\d{3,4})/i);if(!m)return null;return[Math.min(+m[1],+m[2]),Math.max(+m[1],+m[2])]}
 function augmentEaston(r){if(!/Recommandation\s+Easton/i.test(r.textContent||''))return;const range=eastonRange(r);if(!range)return;const [min,max]=range,bow=currentBow();let heading=[...r.querySelectorAll('p,div,h3,h4')].find(el=>/^\s*Mod[eè]les conseill[eé]s\s*:/i.test(el.textContent||''));if(!heading)return;let ul=heading.nextElementSibling;if(!ul||ul.tagName!=='UL')return;const existing=new Set([...ul.querySelectorAll('li')].map(li=>canonical(li.textContent||'')).filter(Boolean));for(const model of EASTON_REFERENCES){if(existing.has(model.key)||!model.bows.includes(bow))continue;const avail=model.spines.filter(s=>s>=min&&s<=max);if(!avail.length)continue;const li=document.createElement('li');li.dataset.aaAddedReference=model.key;li.innerHTML=`<strong>${model.name}</strong> - ${model.material} | spine(s) fabricant dans la plage : <strong>${avail.join(', ')}</strong>`;ul.appendChild(li);existing.add(model.key)} }
 function proposedModels(r){const set=new Set();r.querySelectorAll('li').forEach(li=>{if(li.closest('.merchant-block'))return;const c=canonical(li.textContent||'');if(c)set.add(c)});return set}
 function explainModels(r){r.querySelectorAll('li').forEach(li=>{if(li.closest('.merchant-block'))return;const c=canonical(li.textContent||'');if(!c)return;let why=li.querySelector('.aa-model-why');if(!why){why=document.createElement('div');why.className='aa-model-why';why.style.cssText='margin-top:.28rem;line-height:1.35';li.appendChild(why)}why.innerHTML='<strong>Pourquoi ce modèle :</strong> '+(WHY[c]||'Retenu car ses caractéristiques, son usage et les tailles disponibles sont cohérents avec la configuration sélectionnée ; le choix final reste à confirmer au tir.')})}
 function alignMerchants(){const r=document.getElementById('result');if(!r)return;const models=proposedModels(r);if(!models.size)return;r.querySelectorAll('.merchant-block').forEach(block=>{let kept=0;block.querySelectorAll('.merchant-deals li').forEach(li=>{const title=li.querySelector('a')?.textContent||li.textContent||'';const c=canonical(title);const ok=c&&models.has(c);li.hidden=!ok;li.style.display=ok?'':'none';if(!ok)return;kept++;li.querySelector('.aa-offer-meta')?.remove();const meta=document.createElement('div');meta.className='aa-offer-meta';meta.style.cssText='font-size:.88em;margin-top:.2rem;opacity:.82';meta.textContent=`Correspond au modele propose : ${c} · ${packageLabel(title)}`;li.appendChild(meta)});block.querySelectorAll('.merchant-shop').forEach(shop=>{shop.style.display=shop.querySelector('.merchant-deals li:not([hidden])')?'':'none'});let intro=block.querySelector('.merchant-intro');if(!intro){intro=document.createElement('p');intro.className='merchant-intro';block.prepend(intro)}intro.innerHTML=kept?'<strong>Offres marchands cohérentes :</strong> prix disponibles pour les modèles proposés ci-dessus.':'<strong>Aucune offre correspondante actuellement :</strong> aucun prix présent dans la base marchands pour les modèles proposés.'})}
 function run(){settings();labels();const r=document.getElementById('result');if(r){augmentEaston(r);explainModels(r)}alignMerchants();document.documentElement.dataset.testFixVersion=VERSION}
 let q=false;function schedule(){if(q)return;q=true;requestAnimationFrame(()=>{q=false;run()})}
 function init(){schedule();new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true,characterData:true});document.addEventListener('submit',()=>{setTimeout(schedule,0);setTimeout(schedule,150);setTimeout(schedule,500)},true);document.addEventListener('change',()=>setTimeout(schedule,100),true)}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
