/* Correctifs issus de l'audit du 10/08/2026. */
(() => {
  const originalNormalizeInput = window.normalizeInput;
  const originalScoreModel = window.scoreModel;
  const originalEastonCarbonRecommendation = window.eastonCarbonRecommendation;
  const originalEastonAluRecommendation = window.eastonAluRecommendation;
  const originalVictoryRecurveRecommendation = window.victoryRecurveRecommendation;
  const originalVictoryVxtRecommendation = window.victoryVxtRecommendation;
  const originalCarbonExpressRecommendation = window.carbonExpressRecommendation;
  const originalComputeArcSetup = window.computeArcSetup;
  const originalRenderArcSetup = window.renderArcSetup;
  const originalRenderBarebowArcSetup = window.renderBarebowArcSetup;
  const originalUpdateArcSetupCopyForBowStyle = window.updateArcSetupCopyForBowStyle;
  const originalUpdateSightCopyForBowStyle = window.updateSightCopyForBowStyle;
  function roundedLengthInRange(input,min,max,label){const roundedLength=Math.round(input.arrowLength);if(roundedLength<min||roundedLength>max)return{ok:false,message:`Longueur hors tableau ${label} (${min} a ${max} pouces).`};return null}
  window.normalizeInput=function(input){if(input.shaftMaterial!=="all")return originalNormalizeInput(input);return{...input,shootingProfile:"recurve_all",shootingEnvironment:"mixed",discipline:"target"}};
  window.scoreModel=function(modelName,input,profile){if(input.shaftMaterial!=="all")return originalScoreModel(modelName,input,profile);const outdoor=originalScoreModel(modelName,{...input,shootingProfile:"recurve_outdoor",shootingEnvironment:"outdoor"},profile),indoor=originalScoreModel(modelName,{...input,shootingProfile:"recurve_indoor",shootingEnvironment:"indoor"},profile);return outdoor.score>=indoor.score?outdoor:indoor};
  window.eastonCarbonRecommendation=(input)=>roundedLengthInRange(input,21,34,"Easton carbone")||originalEastonCarbonRecommendation(input);window.eastonAluRecommendation=(input)=>roundedLengthInRange(input,21,32,"Easton alu")||originalEastonAluRecommendation(input);window.victoryRecurveRecommendation=(input)=>roundedLengthInRange(input,23,31,"Victory recurve")||originalVictoryRecurveRecommendation(input);window.victoryVxtRecommendation=function(input){if(roundedLengthInRange(input,23,31,"Victory VXT"))return null;return originalVictoryVxtRecommendation(input)};window.carbonExpressRecommendation=function(input){const light=input.drawWeight<=34&&input.arrowLength<=27;return(light?roundedLengthInRange(input,21,27,"Carbon Express light recurve"):roundedLengthInRange(input,23,32,"Carbon Express recurve series"))||originalCarbonExpressRecommendation(input)};
  window.computeArcSetup=function(input){const setup=originalComputeArcSetup(input),min=2,max=6,a=setup.actualTiller,target=a<min?min:a>max?max:a,expected=Math.round((input.upperTiller-target)*10)/10;setup.tillerRange=[min,max];setup.lowerTiller=expected;setup.lowerGap=Math.round((input.lowerTillerMeasured-expected)*10)/10;setup.tillerTarget=target;setup.tillerAction=a>=min&&a<=max?`Tiller dans la plage de depart conseillee (+${min} a +${max} mm). Conserver puis affiner au tir si necessaire.`:`Tiller hors plage de depart conseillee (+${min} a +${max} mm). Corriger progressivement vers la limite la plus proche.`;setup.adjustment=a>=min&&a<=max?{status:"OK - dans la plage conseillee",advice:`Le tiller mesure (+${a.toFixed(1)} mm) est compris entre +${min} et +${max} mm. Ne modifiez pas les vis uniquement pour viser +6 mm.`}:window.buildTillerAdjustment(a,target);if(Array.isArray(setup.checks))setup.checks=setup.checks.map(line=>line.startsWith("Tiller :")?`Tiller : plage de depart conseillee entre +${min} et +${max} mm, a affiner selon le comportement de l'arc.`:line);return setup};
  window.renderArcSetup=function(input){const result=originalRenderArcSetup(input),output=document.getElementById("arcSetupResult");if(output)output.innerHTML=output.innerHTML.replace(/<strong>Tiller positif vise<\/strong> : \+[^<]+ mm/,'<strong>Plage de tiller conseillee</strong> : +2 a +6 mm').replace(/<strong>Tiller<\/strong> : base visee \+[^|]+\|/,'<strong>Tiller</strong> : plage conseillee +2 a +6 mm |');return result};
  window.renderBarebowArcSetup=function(input){const classical=window.computeArcSetup;window.computeArcSetup=function(i){const s=originalComputeArcSetup(i),min=-2,max=2,a=s.actualTiller,target=Math.max(min,Math.min(max,a)),expected=Math.round((i.upperTiller-target)*10)/10;s.tillerRange=[min,max];s.lowerTiller=expected;s.lowerGap=Math.round((i.lowerTillerMeasured-expected)*10)/10;s.tillerTarget=target;s.tillerAction=a>=min&&a<=max?`Tiller faible/proche de zero (${a.toFixed(1)} mm) : conserver comme base si l'arc est stable, puis valider au tir sur plusieurs crawls.`:`Tiller ${a.toFixed(1)} mm : verifier d'abord la recommandation fabricant puis revenir progressivement vers un tiller faible si necessaire.`;s.adjustment=a>=min&&a<=max?{status:"Base barebow coherente",advice:"Ne cherchez pas a atteindre exactement 0 mm. Validez le comportement de l'arc sur plusieurs crawls."}:window.buildTillerAdjustment(a,target);return s};try{return originalRenderBarebowArcSetup(input)}finally{window.computeArcSetup=classical}};
  document.querySelectorAll(".arc-classic-only p").forEach(p=>{if(p.textContent.includes("Repere de base"))p.innerHTML='Le <strong>band</strong> depend surtout de la taille d\'arc. Le <strong>tiller positif</strong> se calcule ainsi : <strong>tiller haut - tiller bas</strong>. Repere de depart : entre <strong>+2 et +6 mm</strong>.'});
  const upperTillerInput=document.getElementById("upperTiller"),lowerTillerInput=document.getElementById("lowerTillerMeasured");if(upperTillerInput){upperTillerInput.value="";upperTillerInput.placeholder="Ex : 222"}if(lowerTillerInput){lowerTillerInput.value="";lowerTillerInput.placeholder="Ex : 218"}
  window.updateArcSetupCopyForBowStyle=function(style){originalUpdateArcSetupCopyForBowStyle(style);if(window.normalizeBowStyle(style)!=="barebow")return;const ref=document.getElementById("arcSetupDocRef");if(ref)ref.innerHTML='References barebow : <a href="https://www.worldarchery.sport/fr/sport/equipment/barebow" target="_blank" rel="noopener noreferrer">World Archery - Arc nu</a> pour l\'equipement et le stringwalking, et <a href="https://extranet.worldarchery.sport/documents/index.php/Coaches/Accreditation/Coaching_Levels/Coaching_Manual_Level2.pdf" target="_blank" rel="noopener noreferrer">World Archery Coaching Manual Level 2</a> pour les principes de band, tiller, berger button, detalonnage et affinage au tir.'};
  window.updateSightCopyForBowStyle=function(style){originalUpdateSightCopyForBowStyle(style);if(window.normalizeBowStyle(style)!=="barebow")return;const tab=document.getElementById("sightTabButton");if(tab)tab.textContent="Repere palette";const f=document.getElementById("sight-form");if(!f)return;const t=f.querySelector(".subcard h3");if(t)t.textContent="Fiche barebow";const e=document.getElementById("sightEquipment");if(e){const l=e.closest("label"),n=l&&Array.from(l.childNodes).find(x=>x.nodeType===Node.TEXT_NODE&&x.textContent.trim());if(n)n.textContent="\n                Arc / materiel barebow\n                ";e.placeholder="Ex : WNS / Hoyt / palette / berger button"}const notes=document.getElementById("sightNotes");if(notes)notes.placeholder="Ex : crawl 30 m, repere palette, prise de corde, sensations..."};
  localStorage.setItem("sw-cleanup-v1","done");if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));
  let deferredInstallPrompt=null;const isStandalone=()=>window.matchMedia("(display-mode: standalone)").matches||window.navigator.standalone===true;const isIOS=()=>/iphone|ipad|ipod/i.test(navigator.userAgent);
  function installAppSettingsControl(){const body=document.querySelector(".app-settings-body");if(!body||document.getElementById("installAppBtn")||isStandalone())return;const block=document.createElement("div");block.className="app-install-setting";block.style.cssText="margin-top:.9rem;padding-top:.9rem;border-top:1px solid rgba(0,0,0,.12)";const button=document.createElement("button");button.type="button";button.id="installAppBtn";button.textContent="Installer l'application";const status=document.createElement("p");status.id="installAppStatus";status.style.cssText="margin:.5rem 0 0;font-size:.9em";status.textContent="Ajoute Assistant Archer comme une application sur le telephone.";button.onclick=async()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();const choice=await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;status.textContent=choice.outcome==="accepted"?"Installation lancee.":"Installation annulee."}else if(isIOS())status.textContent="Sur iPhone/iPad : Safari > Partager > Ajouter a l'ecran d'accueil.";else status.textContent="Ouvrez le menu du navigateur puis choisissez Installer l'application ou Ajouter a l'ecran d'accueil."};block.append(button,status);body.appendChild(block)}
  window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstallPrompt=e;const s=document.getElementById("installAppStatus");if(s)s.textContent="Pret a installer : touchez Installer l'application."});window.addEventListener("appinstalled",()=>{deferredInstallPrompt=null;document.querySelector('.app-install-setting')?.remove();});installAppSettingsControl();
  function applyBrandIdentity(){document.title="Assistant Archer";let icon=document.querySelector('link[rel="icon"]');if(icon){icon.href="icon-assistant-archer-v11.svg";icon.type="image/svg+xml"}const h=document.querySelector('.hero h1');if(h)h.textContent="Assistant Archer";const p=document.querySelector('.hero > p');if(p)p.textContent="Choisir ses fleches, regler son arc et garder ses reperes.";if(!document.getElementById('aaBrandStyle')){const s=document.createElement('style');s.id='aaBrandStyle';s.textContent=`.app-settings{border-color:var(--line)}.app-settings[open]{box-shadow:0 14px 30px rgba(9,31,55,.18)}`;document.head.appendChild(s)}}
  applyBrandIdentity();
  function loadScript(src,key){if(document.querySelector(`script[data-${key}]`))return;const s=document.createElement("script");s.src=src;s.setAttribute(`data-${key}`,"true");document.head.appendChild(s)}
  loadScript("barebow-guidance.js?v=20260814c","barebow-guidance");loadScript("ui-refactor.js?v=20260810c","ui-refactor");loadScript("onboarding.js?v=20260810d","onboarding");
  queueMicrotask(()=>{try{window.applyBowStyle(window.currentBowStyle())}catch{}});
})();