/* Audit logique TEST v27 : garde-fous de coherence et affichage prudent. */
(() => {
  const VERSION='2026.08.18-test.27';
  function fixSettingsLabel(){const s=document.querySelector('.app-settings-toggle');if(!s)return;s.innerHTML='<span class="gear-icon" aria-hidden="true">⚙</span><span class="settings-label">Réglages Paramètres</span>';s.setAttribute('aria-label','Ouvrir les réglages paramètres');}
  function versionAndUpdate(){const body=document.querySelector('.app-settings-body');if(!body)return;const staticV=document.getElementById('appVersionStatic');if(staticV)staticV.textContent='Version : '+VERSION;let v=document.getElementById('appVersionInfo');if(v)v.remove();if(document.getElementById('appUpdateBtn'))return;const block=document.createElement('div');block.className='app-update-setting';block.style.cssText='margin-top:.9rem;padding-top:.9rem;border-top:1px solid rgba(0,0,0,.12)';const b=document.createElement('button');b.type='button';b.id='appUpdateBtn';b.textContent="Mettre a jour l'application";const s=document.createElement('p');s.id='appUpdateStatus';s.style.cssText='margin:.5rem 0 0;font-size:.9em';s.textContent='Force le chargement de la derniere version TEST.';b.onclick=async()=>{b.disabled=true;s.textContent='Mise a jour...';try{if('serviceWorker'in navigator){const regs=await navigator.serviceWorker.getRegistrations();await Promise.all(regs.map(r=>r.unregister()));}if(window.caches){const keys=await caches.keys();await Promise.all(keys.map(k=>caches.delete(k)));}const u=new URL(location.href);u.searchParams.set('v',Date.now());location.replace(u.toString());}catch(e){s.textContent='Echec de mise a jour. Rechargez la page.';b.disabled=false;}};block.append(b,s);body.appendChild(block)}
  function french(root=document.body){if(!root)return;const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT),a=[];while(w.nextNode())a.push(w.currentNode);for(const n of a){if(!n.nodeValue||!/(crawl|stringwalk|stringwalking)/i.test(n.nodeValue))continue;n.nodeValue=n.nodeValue.replace(/plusieurs crawls/gi,'plusieurs decalages des doigts sous l encoche').replace(/crawls?/gi,'decalage des doigts sous l encoche').replace(/stringwalking/gi,'deplacement des doigts sur la corde').replace(/stringwalk/gi,'deplacement des doigts sur la corde')}}
  function easton(){const r=document.getElementById('result');if(!r||!/Recommandation\s+Easton/i.test(r.textContent||''))return;const w=document.createTreeWalker(r,NodeFilter.SHOW_TEXT),a=[];while(w.nextNode())a.push(w.currentNode);for(const n of a){const m=(n.nodeValue||'').trim().match(/^(\d+)\s+base\s+(\d+)\s*[-–]\s*(\d+)\s*\/\s*eq\.\s*(\d+)$/i);if(!m)continue;const x=Number(m[2]),y=Number(m[3]),box=document.createElement('span');box.className='easton-clear-recommendation';box.style.display='block';box.innerHTML=`<span style="display:block;font-size:.58em;font-weight:700">Plage fabricant : ${Math.min(x,y)}-${Math.max(x,y)}</span><span style="display:block;margin-top:.18em">Repere de depart : groupe/plage fabricant (pas un spine intermediaire invente)</span>`;n.parentNode.replaceChild(box,n);break}r.querySelectorAll('p,li,div').forEach(el=>{const t=el.textContent||'';if(/^\s*Alternatives spine\s*:/i.test(t)||/cote plus souple de la plage Easton est privilegie/i.test(t))el.remove()});r.querySelectorAll('li').forEach(li=>{if(/spine conseille\s+\d+/i.test(li.textContent||''))li.innerHTML=li.innerHTML.replace(/\s*\|\s*spine conseille\s+\d+/i,' | verifier une taille reellement disponible pour ce modele')});r.querySelectorAll('p').forEach(p=>{if(/Niveau de confiance\s*:\s*Elevee/i.test(p.textContent||''))p.innerHTML='<strong>Niveau de confiance</strong> : Moyenne'});if(!r.querySelector('.easton-audit-note')){const p=document.createElement('p');p.className='easton-audit-note';p.innerHTML='<strong>Important :</strong> le tableau Easton peut retourner plusieurs tailles/modeles dans un meme groupe. Le choix final doit etre une taille reellement fabriquee pour le modele retenu.';r.appendChild(p)}}
  function allMaterials(){const r=document.getElementById('result'),m=document.getElementById('shaftMaterial')?.value;if(!r||m!=='all'||r.querySelector('.material-mode-note'))return;const p=document.createElement('p');p.className='material-mode-note';p.innerHTML='<strong>Materiaux = Tous :</strong> les propositions carbone et aluminium sont des options selon l usage ; elles ne sont pas directement comparables comme un classement unique.';r.insertAdjacentElement('afterbegin',p)}
  function labels(){const g=document.getElementById('aaNeedsGuide');if(!g)return;const n=g.querySelector('[data-go="notebook"]'),s=g.querySelector('[data-go="sight"]');if(n)n.textContent='Enregistrer / retrouver mes reglages';if(s)s.textContent='Enregistrer / consulter mes reperes'}
  let pending=false;function run(){if(pending)return;pending=true;requestAnimationFrame(()=>{pending=false;fixSettingsLabel();french();easton();allMaterials();labels();versionAndUpdate()})}
  function init(){document.documentElement.dataset.testFixVersion=VERSION;run();new MutationObserver(run).observe(document.body,{childList:true,subtree:true,characterData:true});document.getElementById('spine-form')?.addEventListener('submit',()=>{setTimeout(run,0);setTimeout(run,150);setTimeout(run,500)},true)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
