/* TEST v32 : conserve les offres et masque seulement les offres non coherentes. */
(() => {
 const VERSION='2026.08.18-test.32';
 function norm(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim()}
 function settings(){const s=document.querySelector('.app-settings-toggle');if(s)s.innerHTML='<span class="gear-icon" aria-hidden="true">⚙</span><span class="settings-label">Réglages Paramètres</span>';const b=document.querySelector('.app-settings-body');if(!b)return;const sv=document.getElementById('appVersionStatic');if(sv)sv.textContent='Version : '+VERSION;document.getElementById('appVersionInfo')?.remove()}
 function labels(){const g=document.getElementById('aaNeedsGuide');if(!g)return;const n=g.querySelector('[data-go="notebook"]'),s=g.querySelector('[data-go="sight"]');if(n)n.textContent='Enregistrer / retrouver mes reglages';if(s)s.textContent='Enregistrer / consulter mes reperes'}
 function packageLabel(title){const t=norm(title);if(/\b(douzaine|lot de 12|12 tubes|12 futs|12 fleches)\b/.test(t))return'lot de 12';if(/\b(unite|a l unite)\b/.test(t)||(/\btube\b/.test(t)&&!/\btubes\b/.test(t)))return'prix a l unite';return'conditionnement a verifier'}
 const ALIASES={
  'avance':['avance','avance sport'],'superdrive micro':['superdrive micro'],'vector':['vector'],'vector ready to shoot':['vector ready to shoot','vector rts'],
  'x10':['x10'],'a/c/e':['a/c/e','ace'],'x10 parallel pro 4 mm':['x10 parallel pro','parallel pro'],'x7':['x7'],'x23':['x23'],'rx7':['rx7'],'xx75 platinum plus':['xx75 platinum plus'],
  'vap v3':['vap v3'],'vap sport':['vap sport'],'vap target':['vap target','vap target v1','vap target elite','vap target sport'],'vxt elite v1':['vxt elite v1','vxt elite'],'vap gamer v3':['vap gamer v3'],'vft gamer v3':['vft gamer v3'],'v-tac 23 elite':['v-tac 23 elite','v tac 23 elite'],'vforce':['vforce'],
  'predator ii':['predator ii'],'maxima red':['maxima red'],'hunter xt':['hunter xt'],'trojan':['trojan'],'nano-pro rz':['nano pro rz','nano-pro rz'],'nano-pro xtreme':['nano pro xtreme','nano-pro xtreme'],'medallion xr':['medallion xr'],'nano sst':['nano sst'],
  'brixxon':['brixxon'],'radius':['radius'],'premiens':['premiens','preminens'],'performa':['performa'],'precium':['precium'],'paragon':['paragon'],'edge':['edge']
 };
 function canonical(v){const t=' '+norm(v)+' ';for(const [key,arr] of Object.entries(ALIASES)){for(const a of arr){const n=norm(a);if(t.includes(' '+n+' ')||t.includes(n))return key}}return''}
 function proposedModels(r){const set=new Set();r.querySelectorAll('li').forEach(li=>{if(li.closest('.merchant-block'))return;const c=canonical(li.textContent||'');if(c)set.add(c)});return set}
 function alignMerchants(){const r=document.getElementById('result');if(!r)return;const models=proposedModels(r);if(!models.size)return;r.querySelectorAll('.merchant-block').forEach(block=>{let kept=0;block.querySelectorAll('.merchant-deals li').forEach(li=>{const title=li.querySelector('a')?.textContent||li.textContent||'';const c=canonical(title);const ok=c&&models.has(c);li.hidden=!ok;li.style.display=ok?'':'none';if(!ok)return;kept++;li.querySelector('.aa-offer-meta')?.remove();const meta=document.createElement('div');meta.className='aa-offer-meta';meta.style.cssText='font-size:.88em;margin-top:.2rem;opacity:.82';meta.textContent=`Correspond au modele propose : ${c} · ${packageLabel(title)}`;li.appendChild(meta)});block.querySelectorAll('.merchant-shop').forEach(shop=>{shop.style.display=shop.querySelector('.merchant-deals li:not([hidden])')?'':'none'});let intro=block.querySelector('.merchant-intro');if(!intro){intro=document.createElement('p');intro.className='merchant-intro';block.prepend(intro)}intro.innerHTML=kept?'<strong>Offres marchands cohérentes :</strong> prix disponibles pour les modèles proposés ci-dessus.':'<strong>Aucune offre correspondante actuellement :</strong> aucun prix présent dans la base marchands pour les modèles proposés.'})}
 function run(){settings();labels();alignMerchants();document.documentElement.dataset.testFixVersion=VERSION}
 let q=false;function schedule(){if(q)return;q=true;requestAnimationFrame(()=>{q=false;run()})}
 function init(){schedule();new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true,characterData:true});document.addEventListener('submit',()=>{setTimeout(schedule,0);setTimeout(schedule,150);setTimeout(schedule,500)},true);document.addEventListener('change',()=>setTimeout(schedule,100),true)}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
