/* Accueil + mini tutoriel Assistant Archer. */
(() => {
  const KEY='assistant-archer-onboarding-v1';
  const CSS=`
  .aa-splash{position:fixed;inset:0;z-index:2147483600;display:grid;place-items:center;background:radial-gradient(circle at 50% 24%,#123763 0,#07182d 43%,#030d1b 100%);color:#fff;transition:opacity .28s ease;overflow:hidden}.aa-splash.is-leaving{opacity:0;pointer-events:none}.aa-splash::before{content:'';position:absolute;width:58vw;height:58vw;max-width:520px;max-height:520px;left:-25%;top:6%;border:1px solid rgba(55,137,231,.08);border-radius:50%;box-shadow:0 0 0 55px rgba(55,137,231,.035),0 0 0 110px rgba(55,137,231,.025)}.aa-splash-inner{position:relative;width:min(88vw,460px);text-align:center}.aa-splash-logo{width:min(42vw,190px);aspect-ratio:1;margin:0 auto 22px;border-radius:25%;filter:drop-shadow(0 0 20px rgba(20,130,255,.38))}.aa-splash-title{margin:0;font-size:clamp(2rem,8vw,3.3rem);font-weight:750;letter-spacing:.22em;line-height:1.08;color:#f5f8fc}.aa-splash-title span{display:block;margin-top:8px;color:#1687ee}.aa-splash-dot{width:7px;height:7px;margin:22px auto 26px;border-radius:50%;background:#1687ee;box-shadow:-38px 0 0 -2px #435a76,38px 0 0 -2px #435a76}.aa-splash-icons{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.aa-splash-icon{aspect-ratio:1;border:1px solid rgba(45,135,226,.35);border-radius:20px;background:linear-gradient(145deg,rgba(17,43,76,.72),rgba(4,19,38,.78));display:grid;place-items:center;box-shadow:inset 0 1px 0 rgba(255,255,255,.04)}.aa-splash-icon svg{width:48%;height:48%;stroke:#eef5ff;stroke-width:2.2;fill:none;stroke-linecap:round;stroke-linejoin:round}.aa-splash-icon:nth-child(2) svg,.aa-splash-icon:nth-child(3) svg{stroke:#1687ee}
  .aa-onboarding{position:fixed;inset:0;z-index:2147483000;display:grid;place-items:end center;padding:16px}.aa-onboarding-backdrop{position:absolute;inset:0;background:rgba(5,15,28,.72);backdrop-filter:blur(3px)}.aa-onboarding-card{position:relative;width:min(520px,100%);padding:22px;border:1px solid rgba(255,255,255,.16);border-radius:22px;background:linear-gradient(160deg,#0d1b2b,#102b4e);color:#fff;box-shadow:0 24px 60px rgba(0,0,0,.4)}.aa-onboarding-card h2{margin:12px 36px 8px 0;color:#fff;font-size:1.35rem}.aa-tutorial-text{margin:0 0 20px;line-height:1.5;color:#e8eef7}.aa-tutorial-close{position:absolute;right:12px;top:10px;width:38px;min-height:38px;padding:0;border:0;background:transparent;color:#fff;font-size:1.8rem}.aa-tutorial-progress{display:flex;gap:6px}.aa-tutorial-progress span{height:5px;flex:1;border-radius:99px;background:rgba(255,255,255,.2)}.aa-tutorial-progress span.is-active{background:#2585e6}.aa-tutorial-actions{display:flex;gap:10px;justify-content:flex-end}.aa-tutorial-actions button{min-width:110px}.aa-tutorial-next{background:#1976d2!important;border-color:#1976d2!important;color:#fff!important}.aa-tutorial-back{background:transparent!important;border-color:rgba(255,255,255,.35)!important;color:#fff!important}@media(min-width:700px){.aa-onboarding{place-items:center}.aa-onboarding-card{padding:28px}}`;
  if(!document.getElementById('aaOnboardingStyle')){const s=document.createElement('style');s.id='aaOnboardingStyle';s.textContent=CSS;document.head.appendChild(s)}
  function showSplash(){const el=document.createElement('div');el.className='aa-splash';el.setAttribute('aria-label','Assistant Archer');el.innerHTML=`<div class="aa-splash-inner"><img class="aa-splash-logo" src="icon-assistant-archer-v11.svg" alt=""><h1 class="aa-splash-title">ASSISTANT<span>ARCHER</span></h1><div class="aa-splash-dot"></div><div class="aa-splash-icons" aria-hidden="true"><div class="aa-splash-icon"><svg viewBox="0 0 24 24"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m15.5 15.5 5 5"/></svg></div><div class="aa-splash-icon"><svg viewBox="0 0 24 24"><path d="M4 7h16M4 12h16M4 17h16"/><circle cx="9" cy="7" r="2"/><circle cx="15" cy="12" r="2"/><circle cx="11" cy="17" r="2"/></svg></div><div class="aa-splash-icon"><svg viewBox="0 0 24 24"><path d="M5 19 19 5M14 5h5v5M5 14v5h5"/></svg></div></div></div>`;document.body.appendChild(el);setTimeout(()=>el.classList.add('is-leaving'),1250);setTimeout(()=>{el.remove();if(!localStorage.getItem(KEY))start()},1580)}
  const steps=[{title:'Bienvenue dans Assistant Archer',text:'L’app propose des pistes pour vous aider à choisir vos flèches et à régler votre arc. Les réglages restent à valider au tir.',tab:null},{title:'1. Flèches',text:'Saisissez votre puissance réellement tirée et la longueur de flèche pour obtenir une base de départ.',tab:'spine'},{title:'2. Réglage de base',text:'Retrouvez band, tiller, détalonnage, centrage et berger, avec des repères à adapter à votre matériel.',tab:'arc-setup'},{title:'3. Réglage dynamique',text:'Testez au tir, observez le résultat et ne modifiez qu’un réglage à la fois.',tab:'dynamic'},{title:'4. Mes réglages et repères',text:'Gardez vos valeurs et vos observations pour retrouver ce qui fonctionne avec votre configuration.',tab:'notebook'}];
  let index=0;
  function selectTab(tab){if(!tab)return;document.querySelector(`.tab-button[data-tab="${tab}"]`)?.click()}
  function closeTutorial(){document.getElementById('aaOnboarding')?.remove();localStorage.setItem(KEY,'done')}
  function render(){document.querySelector('.app-settings[open]')?.removeAttribute('open');let modal=document.getElementById('aaOnboarding');if(!modal){modal=document.createElement('div');modal.id='aaOnboarding';modal.className='aa-onboarding';modal.innerHTML='<div class="aa-onboarding-backdrop"></div><section class="aa-onboarding-card" role="dialog" aria-modal="true" aria-labelledby="aaTutorialTitle"><button class="aa-tutorial-close" type="button" aria-label="Fermer">×</button><div class="aa-tutorial-progress"></div><h2 id="aaTutorialTitle"></h2><p class="aa-tutorial-text"></p><div class="aa-tutorial-actions"><button type="button" class="secondary aa-tutorial-back">Retour</button><button type="button" class="aa-tutorial-next">Suivant</button></div></section>';document.body.appendChild(modal);modal.querySelector('.aa-tutorial-close').onclick=closeTutorial;modal.querySelector('.aa-onboarding-backdrop').onclick=closeTutorial;modal.querySelector('.aa-tutorial-back').onclick=()=>{if(index>0){index--;render()}};modal.querySelector('.aa-tutorial-next').onclick=()=>{if(index===steps.length-1)closeTutorial();else{index++;render()}}}const step=steps[index];selectTab(step.tab);modal.querySelector('#aaTutorialTitle').textContent=step.title;modal.querySelector('.aa-tutorial-text').textContent=step.text;modal.querySelector('.aa-tutorial-progress').innerHTML=steps.map((_,i)=>`<span class="${i===index?'is-active':''}"></span>`).join('');modal.querySelector('.aa-tutorial-back').hidden=index===0;modal.querySelector('.aa-tutorial-next').textContent=index===steps.length-1?'Commencer':'Suivant'}
  function start(){index=0;render()}
  function bindButton(){const body=document.querySelector('.app-settings-body');if(!body)return false;let b=document.getElementById('restartTutorialBtn');if(!b){b=document.createElement('button');b.type='button';b.id='restartTutorialBtn';b.className='secondary';b.textContent='Revoir le mini tutoriel';b.style.marginTop='.7rem';body.appendChild(b)}b.onclick=e=>{e.preventDefault();e.stopPropagation();start()};return true}
  window.startAssistantArcherTutorial=start;let tries=0;const timer=setInterval(()=>{tries++;if(bindButton()||tries>20)clearInterval(timer)},200);setTimeout(()=>{bindButton();showSplash()},350);
})();